// Screenshots of every menu screen: main menu, settings, credits, load, creator, pause, end card.
import { chromium } from "playwright-core";
const SH = "/tmp/claude-0/shots";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const page = await (await browser.newContext({ viewport: { width: +(process.env.W ?? 1280), height: +(process.env.H ?? 720) } })).newPage();
const logs = [];
page.on("pageerror", (e) => logs.push(`[pageerror] ${e.message}`));
await page.goto(`http://localhost:4173/?webgl&debug&chapter=muster&timescale=8`);
await page.waitForFunction(() => performance.getEntriesByName("menu-3d-ready").length > 0, null, { timeout: 60000 });
await page.waitForTimeout(2500);
await page.screenshot({ path: `${SH}/ui-menu.png` });
await page.keyboard.press("ArrowDown");
await page.waitForTimeout(400);
await page.screenshot({ path: `${SH}/ui-menu2.png` });
await page.click("text=设置");
await page.waitForTimeout(800);
await page.screenshot({ path: `${SH}/ui-settings.png` });
await page.keyboard.press("Escape");
await page.click("text=制作人员");
await page.waitForTimeout(1200);
await page.screenshot({ path: `${SH}/ui-credits.png` });
await page.keyboard.press("Escape");
await page.click("#menu >> text=新游戏");
await page.waitForSelector("#creator", { timeout: 400000 });
await page.waitForTimeout(3000);
await page.screenshot({ path: `${SH}/ui-creator.png` });
await page.fill("#creator input[type=text]", "艾琳");
await page.click("#creator [data-act=done]");
await page.waitForTimeout(2000);
await page.evaluate(() => window.__game.pause(true));
await page.waitForTimeout(800);
await page.screenshot({ path: `${SH}/ui-pause.png` });
await page.click("#pause >> text=读取");
await page.waitForTimeout(800);
await page.screenshot({ path: `${SH}/ui-load.png` });
await page.keyboard.press("Escape");
await page.waitForTimeout(300);
await page.keyboard.press("ArrowDown");
await page.waitForTimeout(300);
await page.screenshot({ path: `${SH}/ui-pause2.png` });
console.log(logs.join("\n") || "no page errors");
await browser.close();
