// Non-Poly-Haven third-party assets and libraries, shown on the credits page.
export const EXTRA_CREDITS = [
  { id: "quaternius-ubc", kind: "model", name: "Universal Base Characters", authors: ["Quaternius"], source: "https://quaternius.com/packs/universalbasecharacters.html", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { id: "quaternius-outfits", kind: "model", name: "Modular Character Outfits – Fantasy", authors: ["Quaternius"], source: "https://quaternius.com/packs/modularcharacteroutfitsfantasy.html", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { id: "quaternius-ual", kind: "animation", name: "Universal Animation Library 1 & 2", authors: ["Quaternius"], source: "https://quaternius.com/packs/universalanimationlibrary.html", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { id: "0ad-horse", kind: "model", name: "Horse model, texture and walk animation (0 A.D.)", authors: ["Wildfire Games"], source: "https://play0ad.com", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/", note: "经 ZeroAD-Godot 项目转换为 glTF" },
  { id: "music-frost", kind: "music", name: "Frost in the Northern Winter", authors: ["Kaiser (the-oracle)"], source: "https://opengameart.org/content/frost-in-the-northern-winter", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { id: "music-lament", kind: "music", name: "Fantasy: Lament for a Warrior's Soul", authors: ["RandomMind"], source: "https://opengameart.org/content/fantasy-lament-for-a-warriors-soul", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { id: "fs-627064", kind: "sound", name: "Ambiance_Forest (Birds, wind)", authors: ["KaleidacousticsAudio"], source: "https://freesound.org/s/627064/", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { id: "fs-479790", kind: "sound", name: "R22-05-Two Horses on Dirt Road", authors: ["craigsmith"], source: "https://freesound.org/s/479790/", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { id: "fs-538438", kind: "sound", name: "horse with old cart", authors: ["bruno.auzet"], source: "https://freesound.org/s/538438/", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { id: "lib-babylon", kind: "library", name: "Babylon.js", authors: ["Babylon.js contributors"], source: "https://www.babylonjs.com", license: "Apache-2.0", licenseUrl: "https://github.com/BabylonJS/Babylon.js/blob/master/license.md" },
  { id: "lib-jolt", kind: "library", name: "Jolt Physics / JoltPhysics.js", authors: ["Jorrit Rouwe"], source: "https://github.com/jrouwe/JoltPhysics.js", license: "MIT", licenseUrl: "https://github.com/jrouwe/JoltPhysics.js/blob/main/LICENSE" },
  { id: "lib-meshopt", kind: "library", name: "meshoptimizer", authors: ["Arseny Kapoulkine"], source: "https://github.com/zeux/meshoptimizer", license: "MIT", licenseUrl: "https://github.com/zeux/meshoptimizer/blob/master/LICENSE.md" },
  { id: "lib-basis", kind: "library", name: "Basis Universal", authors: ["Binomial LLC"], source: "https://github.com/BinomialLLC/basis_universal", license: "Apache-2.0", licenseUrl: "https://github.com/BinomialLLC/basis_universal/blob/master/LICENSE" },
];
